### ISSUE TITLE
Tile Layout doesn't display correctly if tiles have varying heights

### ISSUE THREAD

**Issue by acousineau** [fafranco82/swdestinydb#132]
I have this problem with float layouts all the time. Relatively easy fix...
### Before
![screen shot 2017-06-15 at 12 33 19 pm](https://user-images.githubusercontent.com/3373383/27191771-da31b6c8-51c6-11e7-83d0-2ef763a25974.png)

### After
![screen shot 2017-06-15 at 12 34 55 pm](https://user-images.githubusercontent.com/3373383/27191843-118a9fb8-51c7-11e7-95fd-169bc8552772.png)

```css
/* 
2 => number of tiles per row
1 => number of tiles per row - 1
*/
.index-decklist:nth-child(2n - 1) {
    clear: both;
}
```
